# Generated by Django 3.2.7 on 2021-09-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_title'),
        ('blog', '0002_auto_20210922_1619'),
    ]

    operations = [
    ]
