# Generated by Django 3.2.7 on 2021-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
