# Generated by Django 3.2.7 on 2021-10-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210930_1627'),
        ('blog', '0005_auto_20210925_1834'),
    ]

    operations = [
    ]
